repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        description: 'Black code formatter'
        entry: black
        language: system
        files: ^(app/.*|tests/.*|.)
        types: [python]
        stages: [commit]
    -   id: prospector
        name: Prospector
        description: 'This hook runs Prospector: https://github.com/landscapeio/prospector'
        entry: prospector
        language: system
        files: ^(app/.*|tests/.*|.)
        types: [file, python]
        stages: [commit]
